### ISSUE TITLE
Examples to create a minimalistic CPM compliant library

### ISSUE THREAD

**Issue by andersfylling** [TheLartians/CPM.cmake#104]
Hi, for us at the more beginner state that wants to contribute or make our projects more compliant with CPM you have the wiki that states what needs to be added. However, I still struggle a little with it. So I was curious if you were interested in adding a minimalistic library example?

**Comment by TheLartians** [comment]
Hey thanks for your interest in the project! Basically, if your library is CMake compatible it should already work with CPM. The [ModernCppStarter](https://github.com/TheLartians/ModernCppStarter) is actually what I would consider a minimal library example as it enforces many good practices you'd expect from a library. Maybe if you could give a specific example of what you're struggling with I could try to help out better.

**Comment by TheLartians** [comment]
From a quick look at your project it appears you are [defining template methods inside implementation files](https://github.com/andersfylling/sorting-nine-inputs-requires-twenty-five-comparisons/blob/16b2c895fd55449cb0504204dfe2dae8a595f83c/src/sequence.cpp). This does not work because the compiler cannot create an implementation for unknown template arguments. This is why unspecialised templates must be defined completely in public header files.
I just noticed there is actually a [great explanation of this on the official isocpp website](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl).

**Comment by andersfylling** [comment]
Thank you for that insight!

Well, at first I hoped I could simply add a few lines to a few different projects for their CMakeLists.txt file, but I decided to just re-use all your CMakeLists and tools instead. And yes, then it works perfectly =)
