### ISSUE TITLE
Any problem with downloading and caching CPM.cmake in CMake?

### ISSUE THREAD

**Issue by tueda** [TheLartians/CPM.cmake#145]
Hi, thanks for developing the very nice tool. I like the snippet in the Wiki page, [Downloading CPM.cmake in CMake](https://github.com/TheLartians/CPM.cmake/wiki/Downloading-CPM.cmake-in-CMake), which makes it easy to set up CPM in my project just by adding a few lines.

But I was wondering that the downloaded CPM could be also stored in the cache specified by `CPM_SOURCE_CACHE`. Indeed, the following seems to work:
```cmake
set(CPM_DOWNLOAD_VERSION 0.27.2)
if(DEFINED ENV{CPM_SOURCE_CACHE})
  # If CPM_SOURCE_CACHE is given, then use the cache directory also for CPM.
  set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
else()
  set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
endif()

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
  message(STATUS "Downloading CPM.cmake")
  file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()
```
This gives a benefit that repeating downloads of CPM.cmake can be also avoided, and one can create new builds offline if CPM and all dependencies are cached. The disadvantage I can see is only that one needs the 4 additional lines in `CMakeLists.txt`.

Do you see any problem with using a cached CPM.cmake in the above way? I just checked with a small test, so maybe I missed something.

If the above has no problem, then perhaps putting it in the Wiki page would be a good idea, maybe in addition to the original simpler one, if you like.

**Comment by TheLartians** [comment]
Hey, thanks for the suggestion, that's a great idea to solve the issue with downloading the CPM.cmake script on-demand!
One thing to consider is that CPM.cmake also allows setting a cache dir per build directory, e.g. through calling `cmake build -DCPM_SOURCE_CACHE=/path/to/cache`. So in order to get completely consistent behaviour we would need to consider the case `if (CPM_SOURCE_CACHE) ...` before checking the environment.
Another thing might be changing the path to be more consistent with other packages, so something like `$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake` could work.
Besides that I see no issue in adding that to the wiki, I think we could even replace the original version as this extension removes the trade-off of loosing offline configuration.

**Comment by tueda** [comment]
Thanks for your reply and explanation. So, the check would be:
```cmake
if(CPM_SOURCE_CACHE)
  set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
elseif(DEFINED ENV{CPM_SOURCE_CACHE})
  set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
else()
  set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
endif()
```
or if you like the "Don't repeat yourself" principle, maybe:
```cmake
if(CPM_SOURCE_CACHE)
  set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm")
elseif(DEFINED ENV{CPM_SOURCE_CACHE})
  set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm")
else()
  set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake")
endif()
set(CPM_DOWNLOAD_LOCATION "${CPM_DOWNLOAD_LOCATION}/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
```

**Comment by TheLartians** [comment]
Looks good to me! Personally I prefer the first version as the repetition isn't too bad and we save a line of code.

**Comment by TheLartians** [comment]
I've gone ahead and added your suggestion to the wiki.
Actually it even makes sense to always download CPM.cmake on-demand as this avoids code bloat in user's projects. Therefore, the [releases](https://github.com/TheLartians/CPM.cmake/releases/tag/v0.27.3) now include a `add_cpm.cmake` script that contains code to download the specific release. Downloading this script instead of the full source is now the recommended way to use CPM.cmake. 
Thanks a lot for the suggestion!
