### ISSUE TITLE
load fmt as external fail

### ISSUE THREAD

**Issue by westfly** [TheLartians/CPM.cmake#98]
the tag of [fmt](https://github.com/fmtlib/fmt.git) has no v prefix
```
6.1.0
6.1.1
6.1.2
qls
v0.11.0
```
default strategy will add v prefix to VERSION supplying by user.
```
148   if (NOT DEFINED CPM_ARGS_GIT_TAG) 
149     set(CPM_ARGS_GIT_TAG v${CPM_ARGS_VERSION}) 
150   endif()
```
should we give an option to handle this situation as well as VERSION equal master?

**Comment by TheLartians** [comment]
Packages not using `v`-prefixed tags require specifying `GIT_TAG` explicitly and additionally to  `VERSION` to the same value, which I agree feels awkward. I think it makes sense to assume the `v`-prefix by default as it seems to be most common convention on GitHub, but it makes sense to override this on a per-package basis. 

Perhaps we could add an additional option `VERSION_PREFIX` to the package definition e.g.

```cmake
CPMAddPackage(
  NAME fmt
  VERSION 6.1.2
  GITHUB_REPOSITORY fmtlib/fmt
  VERSION_PREFIX ""
)
```

**Comment by TheLartians** [comment]
As it turns out, CMake did not support empty arguments until very recently, which is why using `VERSION_PREFIX ""` will not work. Currently however CPM can take the version from `GIT_TAG` as well, reducing the need for double specification as well. So the current "correct" way to add fmt would be the following.

```cmake
CPMAddPackage(
  NAME fmt
  GIT_TAG 6.1.2 # CPM will take the version from this tag
  GITHUB_REPOSITORY fmtlib/fmt
)
```

I will update the documentation and add fmt as an example accordingly.
